In [3]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
y=np.ones(4,dtype=np.int64)
print(y)
print(type(y))

[1 1 1 1]
<class 'numpy.ndarray'>


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X=np.array([[1,2],[3,4]])
Xmatrix=np.asmatrix(X)
print(Xmatrix)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
x=np.linspace(3,10,50,retstep=True)
print(x)

(array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ]), 0.14285714285714285)


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.transpose(x)
res=y.flatten()
print(res)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(1,10,1,dtype=np.int64)
y=np.split(x,[4,6])
print(y)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=np.array([[1,2],[3,4]])
print("Given Matrix : \n",x)
xinv=np.linalg.inv(x)
print("Inverse of Matrix : \n",xinv)
xdiagsum=np.trace(x)
print("Primary Diagonal sum :",xdiagsum)

Given Matrix : 
 [[1 2]
 [3 4]]
Inverse of Matrix : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Primary Diagonal sum : 5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x=np.array([[1,4],[3,1]])
xsort=np.sort(x,axis=1)
print("Original Matrix : \n",x)
print("Sorted along Second axis : \n",xsort)

Original Matrix : 
 [[1 4]
 [3 1]]
Sorted along Second axis : 
 [[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x=np.array([[1,4],[3,1]])
xsort=np.argsort(x,axis=1)
print("Original Matrix : \n",x)
print("Sorted indices along Second axis : \n",xsort)

Original Matrix : 
 [[1 4]
 [3 1]]
Sorted indices along Second axis : 
 [[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x=np.random.randint(low=0,high=10,size=(2,5))
print("Array : \n",x)

Array : 
 [[8 4 0 0 4]
 [2 6 6 4 9]]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [4]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [6]:
droprow=iris_2d[~np.isnan(iris_2d).any(axis=1)]
#print(droprow)
print(np.size(droprow))
print(np.size(iris_2d))

600
600


Find the correlation between first two columns.

In [ ]:
col1,col2=iris_2d[:,1],iris_2d[:,2]
corr=np.corrcoef(col1,col2)
print(corr)

[[ 1.        -0.4205161]
 [-0.4205161  1.       ]]


Find the mean,median and standard deviation of column 3.

In [ ]:
col3=iris_2d[:,3]
print("Mean is : ",np.mean(col3))
print("Median is : ",np.median(col3))
print("Standard Deviation is : ",np.std(col3))

Mean is :  1.1986666666666668
Median is :  1.3
Standard Deviation is :  0.7606126185881716


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

Find the most frequent value of petal length (3rd column) in iris dataset